services:
  - type: web
    name: meat-for-kings
    runtime: python
    buildCommand: pip install -r requirements.txt && python -c "from app import ensure_indexes; ensure_indexes()"
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    autoDeploy: true
